export const Colors = {
  primary: '#1a56db',
  primaryDark: '#1e429f',
  primaryLight: '#e8f0fe',

  background: '#f8f9fa',
  surface: '#ffffff',
  border: '#e5e7eb',
  borderLight: '#f3f4f6',

  text: '#111827',
  textSecondary: '#6b7280',
  textMuted: '#9ca3af',
  textInverse: '#ffffff',

  success: '#16a34a',
  successLight: '#dcfce7',
  warning: '#d97706',
  warningLight: '#fef3c7',
  error: '#dc2626',
  errorLight: '#fee2e2',
  info: '#2563eb',
  infoLight: '#dbeafe',
  purple: '#7c3aed',
  purpleLight: '#ede9fe',
  indigo: '#4f46e5',
  indigoLight: '#e0e7ff',
  orange: '#ea580c',
  orangeLight: '#ffedd5',
  gray: '#6b7280',
  grayLight: '#f3f4f6',

  statusPending: '#d97706',
  statusPendingBg: '#fef3c7',
  statusQuoteSent: '#2563eb',
  statusQuoteSentBg: '#dbeafe',
  statusConfirmed: '#16a34a',
  statusConfirmedBg: '#dcfce7',
  statusInProduction: '#7c3aed',
  statusInProductionBg: '#ede9fe',
  statusReadyToShip: '#4f46e5',
  statusReadyToShipBg: '#e0e7ff',
  statusShipping: '#ea580c',
  statusShippingBg: '#ffedd5',
  statusDelivered: '#16a34a',
  statusDeliveredBg: '#dcfce7',
  statusCompleted: '#6b7280',
  statusCompletedBg: '#f3f4f6',
  statusCancelled: '#dc2626',
  statusCancelledBg: '#fee2e2',
};
